[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 12.0
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.80
padding = { x = 0, y = 0 }
blur = true
decorations = "none"
dimensions = { columns = 300, lines = 100}

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" }
]

[cursor]
style = { blinking = "Always"}

[selection]
save_to_clipboard = true

# Colors (Alabaster Dark)
# author tonsky

[colors.primary]
background = '#0E1415'
foreground = '#CECECE'

[colors.cursor]
text = '#0E1415'
cursor = '#CECECE'

[colors.normal]
black = '#0E1415'
red = '#e25d56'
green = '#73ca50'
yellow = '#e9bf57'
blue = '#4a88e4'
magenta = '#915caf'
cyan = '#23acdd'
white = '#f0f0f0'

[colors.bright]
black = '#777777'
red = '#f36868'
green = '#88db3f'
yellow = '#f0bf7a'
blue = '#6f8fdb'
magenta = '#e987e9'
cyan = '#4ac9e2'
white = '#FFFFFF'
