[font]
normal = { family = "RobotoMono Nerd Font", style = "Regular" }
size = 12.0
[env]
TERM = "xterm-256color"

[window]
dynamic_padding = true
opacity = 0.99 
padding = { x = 0, y = 0 }
blur = true
#decorations = "none"
dimensions = { columns = 300, lines = 100}

[keyboard]
bindings = [
  { key = "C", mods = "Control", action = "Copy" },
  { key = "V", mods = "Control", action = "Paste" }
]

[cursor]
style = { blinking = "Always"}

[selection]
save_to_clipboard = true


[colors.primary]
background = '#2e3440'
foreground = '#d8dee9'
dim_foreground = '#a5abb6'

[colors.cursor]
text = '#2e3440'
cursor = '#d8dee9'


[colors.normal]
black   = '#3b4252'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#88c0d0'
white   = '#e5e9f0'

[colors.bright]
black   = '#4c566a'
red     = '#bf616a'
green   = '#a3be8c'
yellow  = '#ebcb8b'
blue    = '#81a1c1'
magenta = '#b48ead'
cyan    = '#8fbcbb'
white   = '#eceff4'

[colors.dim]
black   = '#373e4d'
red     = '#94545d'
green   = '#809575'
yellow  = '#b29e75'
blue    = '#68809a'
magenta = '#8c738c'
cyan    = '#6d96a5'
white   = '#aeb3bb'
